name: build

on:
  push:
    branches: [ main ]
    paths-ignore:
      - "README.md"

jobs:
  build:
    strategy:
      matrix:
        ARCH: [ amd64, arm64, arm ]

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
      
      - name: Install GO
        uses: actions/setup-go@v2
        with:
          go-version: 1.16.x

      - name: Install xcaddy
        run: go install github.com/caddyserver/xcaddy/cmd/xcaddy@latest

      - name: Build caddy
        run: |
          GOOS=linux GOARCH=${{ matrix.ARCH }} xcaddy build \
          --with github.com/WingLim/caddy-webhook \
          --output bin/caddy-${{ matrix.ARCH }}
      
      - name: Run UPX
        uses: crazy-max/ghaction-upx@v1
        with:
          files: |
            ./bin/*

      - name: Build caddy docker
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64,linux/arm
          build-args: arch=${{ matrix.ARCH }}
          push: true
          tags: |
            winglim/caddy:latest
            ghcr.io/winglim/caddy:latest
